// <auto-generated />
using System;
using Botsuana.Covid19.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Botsuana.Covid19.Migrations
{
    [DbContext(typeof(EngSoftDoZeroDBContext))]
    [Migration("20210413050340_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Botsuana.Covid19.Model.Dose", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Identificador");

                    b.ToTable("Dose");
                });

            modelBuilder.Entity("Botsuana.Covid19.Model.Vacinado", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("RG")
                        .HasColumnType("text");

                    b.Property<DateTime>("dataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("doseIdentificador")
                        .HasColumnType("integer");

                    b.HasKey("Identificador");

                    b.HasIndex("CPF");

                    b.HasIndex("doseIdentificador");

                    b.ToTable("Vacinado");
                });

            modelBuilder.Entity("Botsuana.Covid19.Model.Vacinado", b =>
                {
                    b.HasOne("Botsuana.Covid19.Model.Dose", "dose")
                        .WithMany()
                        .HasForeignKey("doseIdentificador");
                });
#pragma warning restore 612, 618
        }
    }
}
